#!/bin/bash

set -e

if [[ -n "$APT_ALL_REPOS" ]] ; then
	codename=$(cat /etc/os-release | grep ^VERSION_CODENAME | awk -F= '{print $2}')
	cat <<-END > /etc/apt/sources.list
		deb http://archive.ubuntu.com/ubuntu $codename main restricted universe multiverse
		deb-src http://archive.ubuntu.com/ubuntu $codename main restricted universe multiverse

		deb http://archive.ubuntu.com/ubuntu $codename-backports main restricted universe multiverse
		deb-src http://archive.ubuntu.com/ubuntu $codename-backports main restricted universe multiverse

		deb http://archive.ubuntu.com/ubuntu $codename-security main restricted universe
		deb-src http://archive.ubuntu.com/ubuntu $codename-security main restricted universe

		deb http://archive.ubuntu.com/ubuntu $codename-updates main restricted universe multiverse
		deb-src http://archive.ubuntu.com/ubuntu $codename-updates main restricted universe multiverse
END
fi

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes $@
