#!/bin/bash

set -e

export EP_RUN=/var/local/container_initialized

function log
{
	echo "$(date +%Y-%m-%d_%H:%M:%S) | $(basename $0) | $@"
}
export -f log

# 1 - template / defaults prefix
# 2 - target
# 3 - shell format (optional)
function render_template
{
	log "Generating: $(basename $2) ..."
	if [[ -f "$1.defaults" ]] ; then
		while IFS='=' read -r key value
		do
			eval "export $key=\${$key:=$value}"
			log "   $key=$(eval echo \$$key)"
		done < "$1.defaults"
	fi

	if [[ -z $3 ]] ; then
		envsubst < "$1.template" > "$2"
	else
		envsubst "$3" < "$1.template" > "$2"
	fi
}
export -f render_template

for i in /etc/entrypoint.d/*
do
	if [[ -f $i && -x $i ]] ; then
		log "Invoking: $(basename $i) ..."
		$i "$@"
	fi
done

echo "Container initialized on $(date +%Y-%m-%d_%H:%M:%S) by PID $BASHPID" > $EP_RUN

if [[ -n $EP_USER ]]  && [[ $EP_USER != "root" ]] ; then
	log "User: $EP_USER"
	set -- su --login "$EP_USER" --command='"$0" "$@"' -- "$@"
fi

log "Launching:" $@ "..."
exec "$@"

