#!/bin/bash

set -e

export EP_RUN=/var/local/container_initialized

function log
{
	echo "$(date +%Y-%m-%d_%H:%M:%S) | $(basename $0) | $@"
}
export -f log

# Wait for the container to finish initializing
if [[ -e "$EP_RUN" ]] ; then
	for i in /etc/healthcheck.d/*
	do
		if [[ -f $i && -x $i ]] ; then
			log "Invoking: $(basename $i) ..."
			$i "$@"
			[[ $? -ne 0 ]] && exit $?
		fi
	done
fi

exit 0

