#!/bin/bash

if [[ "$DOCKER_TAG" != "latest" ]] ; then
	tag_prefix="${DOCKER_TAG}-"
fi

custom="${DOCKER_REPO}:${tag_prefix}$(date '+%Y%m%d%H%M')"
echo "Tagging and pushing: $custom ..."
docker tag $IMAGE_NAME $custom
docker push $custom

custom="${DOCKER_REPO}:${tag_prefix}${SOURCE_COMMIT:0:12}"
echo "Tagging and pushing: $custom ..."
docker tag $IMAGE_NAME $custom
docker push $custom

