#!/bin/bash

set -e -o pipefail

if [[ -n "${APT_ALL_REPOS}" ]] ; then
	codename=$(grep ^VERSION_CODENAME /etc/os-release | awk --field-separator= '{print $2}')
	cat <<-END > /etc/apt/sources.list
		deb http://archive.ubuntu.com/ubuntu ${codename} main restricted universe multiverse
		deb-src http://archive.ubuntu.com/ubuntu ${codename} main restricted universe multiverse

		deb http://archive.ubuntu.com/ubuntu ${codename}-backports main restricted universe multiverse
		deb-src http://archive.ubuntu.com/ubuntu ${codename}-backports main restricted universe multiverse

		deb http://archive.ubuntu.com/ubuntu ${codename}-security main restricted universe
		deb-src http://archive.ubuntu.com/ubuntu ${codename}-security main restricted universe

		deb http://archive.ubuntu.com/ubuntu ${codename}-updates main restricted universe multiverse
		deb-src http://archive.ubuntu.com/ubuntu ${codename}-updates main restricted universe multiverse
END
fi

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends --yes "$@"

